Repository m-lab/etl-gardener, pull requests merged in 2018-10, with the labels that each got.

#92 Add NDT deployment & service to gardener
  k8s/data-processing-cluster/deployments/etl-gardener-ndt.yml
  k8s/data-processing-cluster/services/etl-gardener-ndt-service.yml
Labels: Sprint 17, Task

#96 Remove references to measurement-lab
  cloud/bq/README.md
  cloud/bq/dedup.go
  cloud/cloud.go
  cmd/gardener/README.md
Labels: Sprint 18

#88 plumb context everywhere
  cloud/bq/dedup.go
  cloud/bq/sanity.go
  cloud/tq/tq.go
  cloud/tq/tq_integration_test.go
  cmd/gardener/gardener.go
  reproc/dispatch.go
  reproc/dispatch_test.go
  rex/rex.go
  rex/rex_bb_test.go
  rex/rex_test.go
  state/state.go
  state/state_bb_test.go
  state/state_test.go
Labels: Sprint 18

#97 Use stiface to allow test fake injection
  cloud/tq/tq.go
  cloud/tq/tq_integration_test.go
  cmd/gardener/gardener.go
  rex/rex.go
  rex/rex_bb_test.go
  rex/rex_test.go
Labels: Sprint 18

#93 Update Sidestream start date and use standard DATASET names
  k8s/data-processing-cluster/deployments/etl-gardener-sidestream.yml
Labels: Sprint 17, Task

#103 Some quick test coverate wins in the state package.
  state/state.go
  state/state_test.go
Labels: Sprint 18, Task

#108 Add task date of most recent datastore update, per state
  metrics/metrics.go
  state/state.go
Labels: Sprint 18

#110 Use archive-mlab-oti instead of scraper-mlab-oti
  k8s/data-processing-cluster/deployments/etl-gardener-sidestream.yml
Labels: 1, Sprint 18
