Repository m-lab/etl-gardener, pull requests merged in 2019-02, with the labels that each got.

#130 delay deleting dedup source
  rex/rex.go
Labels: 2019, Sprint 3

#136 Increase delay to 60 minutes
  cloud/bq/dedup.go
  cloud/bq/sanity.go
  rex/rex.go
Labels: 2019, Sprint 4

#142 promauto and prometheusx
  cloud/tq/tq.go
  cloud/tq/tq_test.go
  cmd/gardener/gardener.go
  metrics/metrics.go
  metrics/metrics_test.go
Labels: 1, 2019, Sprint 5, Task
